# Generated by Django 3.2.7 on 2022-07-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('telefon', models.CharField(max_length=14)),
                ('status', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
