# Generated by Django 3.2.7 on 2022-07-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijoz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mijoz',
            name='citi',
            field=models.CharField(choices=[('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Farg`ona', 'Farg`ona'), ('Jizzax', 'Jizzax'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ('Qoraqalpogʻiston', 'Qoraqalpogʻiston'), ('Samarqand', 'Samarqand'), ('Sirdaryo', 'Sirdaryo'), ('Surxondaryo', 'Surxondaryo'), ('Toshkent', 'Toshkent'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Xorazm', 'Xorazm')], default=1, max_length=40),
            preserve_default=False,
        ),
    ]
