# Generated by Django 3.2.7 on 2022-07-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijoz', '0002_mijoz_citi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mijoz',
            name='citi',
            field=models.CharField(blank=True, choices=[('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Farg`ona', 'Farg`ona'), ('Jizzax', 'Jizzax'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ('Qoraqalpogʻiston', 'Qoraqalpogʻiston'), ('Samarqand', 'Samarqand'), ('Sirdaryo', 'Sirdaryo'), ('Surxondaryo', 'Surxondaryo'), ('Toshkent', 'Toshkent'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Xorazm', 'Xorazm')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='mijoz',
            name='status',
            field=models.BooleanField(blank=True, default=None),
        ),
    ]
