# Generated by Django 3.2.7 on 2022-07-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijoz', '0003_auto_20220702_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mijoz',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
